### ISSUE TITLE
Update python requirements for ipython

### ISSUE THREAD

**Issue by CasperWA** [aiidalab/aiidalab#123]
https://github.com/aiidalab/aiidalab/blob/6dcc3cc263291146be059bca587d4fca9b21b634/requirements.txt#L90

This Python requirement should be changed to "3.7", since this is the minimum requirement for this version of ´ipython` (see also [here](https://pypi.org/project/ipython/7.18.1/)).

I found this issue when trying to install the latest version of `aiidalab` in a Python 3.6 environment, which now doesn't work, because the latest `ipython` version here is `7.16.1` (not `7.18.1` as required above).

Furthermore, it would be good to write the minimum required Python version for `aiidalab` in the README clearly as well as in `setup()` in `setup.py`.

**Comment by yakutovicha** [comment]
Since we no longer use the `requirements.txt` file, the issue can be closed.
