### ISSUE TITLE
AiiDAlab apps: My first app

### ISSUE THREAD

**Issue by CasperWA** [aiidalab/aiidalab#164]
An extremely simplistic example of how an app may be set up after having created an app with either the cookiecutter or the manual way.

The "scaffolding" for this is/has been added in #161.

**Comment by csadorf** [comment]
Relevant links for this issue:
- https://github.com/aiidalab/aiidalab-app-cutter
- https://github.com/aiidalab/aiidalab-widgets-base/blob/develop/wizard_apps.ipynb
- https://github.com/aiidalab/aiidalab-hello-world
- https://github.com/aiidalab/aiidalab-home/wiki/Make-your-own-app

**Comment by ltalirz** [comment]
This will be incorporated into https://aiidalab.readthedocs.io/en/latest/app_development/create.html

Relevant links for this issue:

 - [ ] https://github.com/aiidalab/aiidalab-app-cutter
 - [ ] https://github.com/aiidalab/aiidalab-widgets-base/blob/develop/wizard_apps.ipynb
 - [ ] https://github.com/aiidalab/aiidalab-hello-world
 - [x] https://github.com/aiidalab/aiidalab-home/wiki/Make-your-own-app Looks like this wiki page was anyhow the guideline for the docs page

**Comment by csadorf** [comment]
>     * [x]  https://github.com/aiidalab/aiidalab-hello-world
>       @csadorf Is this the default output of the cookiecutter or did you make some extra changes?
>       I've just added a link from the cookiecutter.

I believe that we might some small changes after originally creating it with the cookiecutter. Maybe just create a new app with the CC and then run a diff against the hello-world app?

**Comment by ltalirz** [comment]
This is now fixed in the [`develop` branch of the docs](https://aiidalab.readthedocs.io/en/develop/app_development/index.html) (which should become the `latest` one as well).

The linked aiidalab-widgets-docs are not yet up to date because the docs are failing to build, but otherwise all of the points have been addressed. Closing.
