### ISSUE TITLE
ReadTheDocs CI not triggering

### ISSUE THREAD

**Issue by chrisjsewell** [aiidalab/aiidalab#167]
In #162 I turned on https://docs.readthedocs.io/en/latest/pull-requests.html (see https://readthedocs.org/dashboard/aiidalab/advanced/), but it does not seem to be triggering in e.g. #166
This should trigger like, for example, in https://github.com/aiidateam/plumpy/pull/216:

<img width="835" alt="image" src="https://user-images.githubusercontent.com/2997570/112450268-839ff680-8d54-11eb-9e98-affc92277291.png">

I'm not admin on this package, so I can't have a look at the webhook settings, to see if there are any issues there (see https://docs.readthedocs.io/en/stable/pull-requests.html#troubleshooting)

Note I had an issue with the PR CI in quantum-mobile (https://github.com/readthedocs/readthedocs.org/issues/7381), but I don't think this is the same, and I've used it fine in many other packages

cc @yakutovicha @csadorf

**Comment by csadorf** [comment]
@chrisjsewell I just escalated your privileges so you should have access to the configuration.

I checked the webhooks configuration myself and everything seems to be in order and the web hook as also been triggered. However, I don't have access to the RTD settings, maybe you or @yakutovicha could add me as maintainer there?

**Comment by yakutovicha** [comment]
>  @yakutovicha could add me as maintainer there?

Just added.

**Comment by csadorf** [comment]
> > @yakutovicha could add me as maintainer there?
> 
> Just added.

I can't find any issue since it's really only a simple checkbox. So no idea why this isn't working.

**Comment by chrisjsewell** [comment]
Just added Pull Requests to the webhook, which should do it hopefully:

![image](https://user-images.githubusercontent.com/2997570/112465230-c79af780-8d64-11eb-8504-7c10d3d33b10.png)

**Comment by chrisjsewell** [comment]
So from #168 its now triggering, but having the same issue as I've had for quantum-mobile.

From https://docs.readthedocs.io/en/stable/pull-requests.html#troubleshooting, I think this should be present in https://github.com/organizations/aiidalab/settings/oauth_application_policy:

![image](https://user-images.githubusercontent.com/2997570/112467508-6aed0c00-8d67-11eb-8fa3-ae6f6309aeb9.png)

As, for example, it is in https://github.com/organizations/aiidateam/settings/oauth_application_policy

I'm not sure if maybe it is acting via my github account, and I don't (or at least didn't) have the necessary org/repo permissions;
maybe try removing me as a maintainer on https://readthedocs.org/dashboard/aiidalab and resyncing the webhook 🤷

**Comment by yakutovicha** [comment]
> maybe try removing me as a maintainer on https://readthedocs.org/dashboard/aiidalab and resyncing the webhook 🤷

Removed - resynced - added you back

**Comment by chrisjsewell** [comment]
Grr still don't see it in https://github.com/organizations/aiidalab/settings/oauth_application_policy
Somehow it needs to magically get added there

**Comment by chrisjsewell** [comment]
sorted 👍
