### ISSUE TITLE
Use local metadata file to better support non-registered apps

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab#201]
thanks to Dave Wecker for raising this

> If you use the cookie cutter to create an app, meta data (like title, author…) won’t show up correctly in the home page because it assumes that it’s in the app registry (and thus fails). It would be good for it to fall back to the local app instance where all the information already exists (since we aren’t going to be using the registry (at least for now)).

**Comment by ltalirz** [comment]
@csadorf can you point me to where this should be fixed? this looks quite straightforward

**Comment by csadorf** [comment]
@ltalirz You would probably want to start here: https://github.com/aiidalab/aiidalab/blob/77fed765c6b2b9b7b1311905415100b1dabac2e1/aiidalab/app.py#L85-L88

One thing to look out for is how to handle releases in that case, because they **must** be come from the registry. So in that case we would simply have no releases available. That's fine, but just something to look out and test for.

**Comment by csadorf** [comment]
@ltalirz Furthermore, app metadata is defined through the registry, similar to how PyPI stores metadata about a package. So simply sourcing it from the repository breaks a lot of assumptions. So I would like to caution a little bit about considering this _straightforward_.

**Comment by csadorf** [comment]
As an additional comment on this issue. In the latest revision of the registry, we removed the assumption that an app must have a "metadata.json" file, instead the metadata could be directly declared as part of the registry entry. That may have been a bit short-sighted, but one motivation was to generalize the registry concept and also allow for the registration of codes that may not necessarily have a public code repository associated with it. This would allow us to use the registry in contexts other than AiiDAlab. Apps can still reference a metadata file hosted as part of the app source code using the `$ref` keyword, see the [registry README](https://github.com/aiidalab/aiidalab-registry#readme) for details.

Obviously, this was maybe a bit short-sighted when it comes to this particular issue. I suggest that as a stop-gap measure to streamline the installation of apps without registry entry, we either (A) remove the requirement that apps have any metadata at all and make sure that the home app does not complain about this, or (B) fallback to parsing the metadata file from the setup.cfg or local metadata file after all (the exact search path would actually be `[.aiidalab/][metadata.[y[a]ml|json]`). For solution (B) we would then have to re-define the metadata declared as part of the registry simply as a "default" or "override" for maintain backwards-compatibility.
