### ISSUE TITLE
one-line description of AiiDAlab

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab#203]
The AiiDAlab is currently described in the docs as 

> AiiDAlab is an environment for users with diverse expertise to access and run computational workflows embedded in AiiDAlab apps.

I propose to try and make this sentence as bit more concrete ("users with diverse expertise" isn't clear to me; and "AiiDAlab apps" is self-referencing).

The paper describes it as

>  AiiDAlab is a web platform that enables computational scientists to package scientific workflows and computational environments and share them with their collaborators and peers.

I like this already a lot better. I think it captures the purpose of the AiiDAlab quite precisely, and I propose we use it in the docs as well.

To me, jupyter is a core part of the AiiDAlab infrastructure, so if it was up to me I would probably mention it in the sentence but I recall that @csadorf may disagree

**Comment by csadorf** [comment]
I think the second paragraph you quoted described it quite well. We could probably workshop it a bit more, but it's certainly much better than the first one.
