### ISSUE TITLE
docs: hooking up your IDE for AiiDAlab app development

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab#248]
The Jupyter environment is fine for tinkering around but when one wants to start developing an app from scratch, it can make a lot of sense to do that in the IDE of your choice.

One issue that many users will run into is that they can't edit the files in the `~/aiidalab` folder because it is owned by a different user (id `1000`).

In order to fix this, do:
```bash
sudo chown 1000:1000 -R ~/aiidalab/apps  # just to be safe in case user has already tinkered with it
sudo usermod -a -G 1000 <your-username>  # add your user to aiidalab user group
sudo chmod -R g+w ~/aiidalab/apps        # let group members edit apps   
```
Then, log out and log in again (the `groups` command should now list the new group for id `1000`).

I suggest that this be added to the AiiDAlab documentation, e.g. as a new top-level heading "Hooking up your IDE" in https://aiidalab.readthedocs.io/en/latest/app_development/create.html

What do you think?

P.S. Since you are symlinking stuff there, maybe changing permissions for the entier `apps` folder is already too much and one should do it only for the folder of the app one is interested in.

**Comment by ltalirz** [comment]
Pinging @unkcpz - you may have been doing something similar (?)

**Comment by unkcpz** [comment]
@ltalirz Yes, and besides using `chmod` I used another command in the host machine to grant the permission to other UID. But I don't remember the command and it has other problem with using vscode or like in using the git. 
I think for the aiidalab apps development, it is much easier to use the 'attach to container' feature of vscode and I have added this in the documentation already.

**Comment by ltalirz** [comment]
I see, thanks! Somehow I missed this tip at the top of the docs page.

Two small follow-up questions:
- I guess by default you are `root` when you enter the container; did you add some further settings to enter as the AiiDA user?
- Do the server components have to be re-installed in the container whenever you start a new one (I guess they do?)


P.S. In case someone else is running the container remotely and needs to connect from a Windows machine with WSL: you may need to enable this remote container setting:
![image](https://user-images.githubusercontent.com/1053245/147086902-0dd86d06-ea4a-4bbd-89c5-67a338161dab.png)

**Comment by unkcpz** [comment]
> I guess by default you are root when you enter the container; did you add some further settings to enter as the aiida user when using VSCode?

Sure, in order to install all extensions and use git seamless, I set the following configuration, here is how to code in vscode as aiida  user. First attach to container, then ctrl+shift+p to call 'open container configure file' and add "remoteUser": "aiida",  in the dict.

```
{
	"workspaceFolder": "/home/aiida/apps/aiidalab-widgets-base",
	"remoteUser": "aiida",
	"extensions": [
		"batisteo.vscode-django",
		"donjayamanne.python-environment-manager",
		"donjayamanne.python-extension-pack",
		"KevinRose.vsc-python-indent",
		"ms-python.python",
		"ms-python.vscode-pylance",
		"ms-toolsai.jupyter",
		"ms-toolsai.jupyter-keymap",
		"ms-toolsai.jupyter-renderers",
		"njpwerner.autodocstring",
		"VisualStudioExptTeam.vscodeintellicode",
		"wholroyd.jinja"
	]
}
```

**Comment by unkcpz** [comment]
> Do the vscode server components have to be re-installed in the container whenever you start a new one? I guess yes, since they go into /root/.vscode-server. Might be useful to put them inside /home/aiida instead.

With the configuration I mentioned above, maybe the components are go into the `home/aiida`?

**Comment by ltalirz** [comment]
> With the configuration I mentioned above, maybe the components are go into the `home/aiida`?

Yes, they do - thanks for sharing the config option.
With this configuration I agree that the remote container plugin is the most convenient option for VSCode.

It might be worth adding the instruction to add the `"remoteUser"` setting to the workspace configuration - quite impressive that it can go Windows => WSL => Remote machine => container.
And it may still be worth mentioning alternative approaches like the one I outlined above for people who don't use VSCode.
