### ISSUE TITLE
Automatically identify broken environment

### ISSUE THREAD

**Issue by csadorf** [aiidalab/aiidalab#278]
As was described in #277 , it is possible to inadvertently break the AiiDAlab environment and lose access to the system. It would be good to automatically detect this state and initiate or at least suggest a reset to the user.

**Comment by danielhollas** [comment]
@yakutovicha @unkcpz I think this one can be closed.

**Comment by unkcpz** [comment]
Yes, agree. Fixed in https://github.com/aiidalab/aiidalab/commit/f5cbaa39b147bdc2bf20f198523d282c87ee3baf  closed.
