### ISSUE TITLE
Can't install apps with the newest version of aiidalab (22.07.0)

### ISSUE THREAD

**Issue by cpignedoli** [aiidalab/aiidalab#307]
Recently, we update aiidalab to version 22.07.0, and after the update, some of our apps cannot be installed with the error message: "Failed to install dependencies". During the installation no dependencies were installed as they were all present.
![aiidalab-bug](https://user-images.githubusercontent.com/22955065/182326703-f6800777-0a68-4109-821b-1ce229459187.png)

Downgrading aiidalab to version 22.06.0 resolves the issue

**Comment by yakutovicha** [comment]
@csadorf would you be able to have a look?

**Comment by csadorf** [comment]
> @csadorf would you be able to have a look?

Yes, I will check that.

**Comment by csadorf** [comment]
Should be resolved in release https://github.com/aiidalab/aiidalab/releases/tag/v22.07.1 .
