### ISSUE TITLE
modify the is_compatible() function too look at the constraints instead of the current environment

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab#318]
After migrating docker stack to support AiiDA 2.x, most apps in app store would incompatible since they are specifically set to dependent on aiida-core~=1.0. We need to disallow the user to install the old versions of these apps until they have aiida-core 2.0 supported.

The `is_compatible()` function will do this check,
https://github.com/aiidalab/aiidalab/blob/04f295b6eb8aee851a4eb3f538369dd441ce3ea9/aiidalab/app.py#L258-L259

**Comment by yakutovicha** [comment]
@unkcpz could you take care of that?

**Comment by unkcpz** [comment]
Sure! Please assign it to me, I can not do it with my phone somehow.

**Comment by danielhollas** [comment]
@unkcpz I've bumped this issue in priority to High because I think the users are already having an issues with this with QeApp, and will have an issue also once we release AWB 2.0.

**Comment by unkcpz** [comment]
No problem, I'll focus on it in the coming weeks.
