### ISSUE TITLE
App dependencies should be installed in user mode

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab#322]
In the old Docker stack image, the conda environment in `/opt/conda` was not writeable by the `aiida` user.
As a side-effect of that, when the AiiDAlab app was installed via pip, its declared dependencies (and the app itself) was installed in the `home/aiida/.local` directory. Thus these dependencies persisted between different container invocation since they were stored in the home volume / directory.

In the new full-stack image, the conda environment is writeable by the `jovyan` user, hence pip default to system-wide installation. Therefore, the installed dependencies disappear when the container exits. In the next invocation, the Apps won't load due to missing dependencies.

The possible fix for this is very simple, just add the `--user` argument pip here:

https://github.com/aiidalab/aiidalab/blob/1093f7e4e9f7ef4e26733e69f5fde5bee71cd7ef/aiidalab/utils.py#L203

@unkcpz I am very surprised this did not come up earlier. Did you not observe this with QeApp?
If you agree with the proposed fix I will prepare a PR.

**Comment by danielhollas** [comment]
I do not have sufficient privileges for this repo, but I think this should be an urgent issue, unless I have somehow misdiagnosed it.

**Comment by unkcpz** [comment]
I think the initial design is the things installed with pip will go to the local conda folder at https://github.com/aiidalab/aiidalab-launch/blob/0c74626c0e0077e429b535f6df3b38704e8ab92e/aiidalab_launch/instance.py#L102-L106? 
I didn't pay attention to the dependencies with QeApp, since it always has some dependencies issues to fix and I always run pip install before.

**Comment by danielhollas** [comment]
I think the conda mount is a separate thing. I never really understood the use case, but in any case that's for when you're installing via conda. 

The aiidalab apps and their dependencies are installed with pip and were always going to `/home/aiida/.local` afaik.

**Comment by danielhollas** [comment]
@yakutovicha would you mind taking a look and comment on this issue. I think this is important to resolve.

**Comment by unkcpz** [comment]
Hi @danielhollas, I think you are right, I just notice I had the same issue with QeApp, which already happened but I didn't pay attention and to check it. 
Using the `--user` will install the packages to the local home folder which is mounted by `aiidalab-launch` automatically. We should also make sure this `/home/jovyan/.local` path for python packages is in the path and go before the `/opt/conda`.

**Comment by danielhollas** [comment]
Okay, thanks. Do you want to tackle this or should I work on it?

**Comment by unkcpz** [comment]
Can you open a PR and I'll give it a test?

**Comment by danielhollas** [comment]
Wil do, thanks.

Dne po 21. 11. 2022 12:03 odp. uživatel Jusong Yu ***@***.***>
napsal:

**Comment by danielhollas** [comment]
While testing the fix in #323 locally, I've ran into an _interesting_ problem. My app was not loading at all! No errors thrown in the UI, no errors in the notebook. Only after looking the the JupyterServer logs and browser console I realized the error came from JS side.

Concretely, file `/static/nglview-js-widgets.js` could not be loaded. It looks like when the package `nglview` is installed into ~/.local, the jupyter labextension is not registered and the package does not work. I have verified that when I uninstalled nglview and installed it to `/opt/conda`, things started working. 

Here are the files that get installed 

```
    /opt/conda/bin/nglview
    /opt/conda/etc/jupyter/nbconfig/notebook.d/nglview-js-widgets.json
    /opt/conda/lib/python3.9/site-packages/nglview-3.0.3.dist-info/*
    /opt/conda/lib/python3.9/site-packages/nglview/*
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/package.json
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/0de3b51742ed3ac61435875bccd8973b.png
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/133.0c12809866ed16ed02fe.js
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/208a290102a4ada58a04de354a1354d7.png
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/325.0f8271db6262c6939811.js
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/325.0f8271db6262c6939811.js.LICENSE.txt
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/421.04c3327cf7f16704c3b2.js
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/421.04c3327cf7f16704c3b2.js.LICENSE.txt
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/534.eaec54f1d3737a7e98b9.js
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/568.bafd4ba9bc687cad6615.js
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/73a1fd052c9d84c0ee0bea3ee85892ed.png
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/755.096b3c4de99557ca2b8c.js
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/755.096b3c4de99557ca2b8c.js.LICENSE.txt
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/776.5c1b8b0dcd384e09bac7.js
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/963.c74810793d3d55c01a23.js
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/971364734f3b603e5d363a2634898b42.png
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/a4c733ec4baef9ad3896d4e34a8a5448.png
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/bf27228a7d3957983584fa7698121ea1.png
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/remoteEntry.4560fdad4055be520b35.js
    /opt/conda/share/jupyter/labextensions/nglview-js-widgets/static/style.js
    /opt/conda/share/jupyter/nbextensions/nglview-js-widgets/extension.js
    /opt/conda/share/jupyter/nbextensions/nglview-js-widgets/index.js
    /opt/conda/share/jupyter/nbextensions/nglview-js-widgets/index.js.map
```

User installation has the same structure, but `/opt/conda` is `/home/jovyan/.local/`.

I see two ways to fix this:

1. Somehow figure out how to configure the Jupyter server so that the js extensions can be loaded from `~/.local/share/jupyter/`. 

2. Install AWB by default, directly into the AiiDAlab Docker image.

3. Install nglview by default into AiiDAlab Docker image.

Option one would be a more general and clean solution, and needs to be done eventually so that other packages are not affected by this issue.

Option 3 seems as the most straightforward hotfix.

Option 2 might be interesting as a short term fix. I'd assume that majority of AiiDAlab apps depend on AWB anyway, so it makes sense to me if it comes pre-installed. This would also save a bit of startup time, and perhaps may lead to less dependency conflicts. Disadvantage is bigger Docker image (though if we do `https://github.com/aiidalab/aiidalab-widgets-base/issues/392` it might not be as bad.

In any case, this issue is currently a blocker for a proper AiiDA 2.0 support in AiiDAlab I think.

CC @yakutovicha @unkcpz

**Comment by danielhollas** [comment]
The jupyter notebook extensions installed locally are not being picked up by jupyter because of missing config path.
Setting `JUPYTER_CONFIG_PATH=/home/jovyan/.local/etc/jupyter` seems to fix it.

Here's the output of `jupyter --paths` after the fix

```
config:
    /home/jovyan/.local/etc/jupyter
    /home/jovyan/.jupyter
    /opt/conda/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/jovyan/.local/share/jupyter
    /opt/conda/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /home/jovyan/.local/share/jupyter/runtime
```

And here's a list of nbextensions after the fix (this includes some extensions coming from my app).

```
$ jupyter nbextension list
Known nbextensions:
  config dir: /home/jovyan/.local/etc/jupyter/nbconfig
    notebook section
      ipytree/extension  enabled 
      - Validating: OK
      ipywidgets_extended/extension  enabled 
      - Validating: OK
      nglview-js-widgets/extension  enabled 
      - Validating: OK
      widget_periodictable/extension  enabled 
      - Validating: OK
  config dir: /opt/conda/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      appmode/main  enabled 
      - Validating: OK
```

This seems like a bug in the Jupyter Docker image that we should report, but in the meantime I'll open a PR on aiidalab-docker-stack to fix this on our end. Then I think we can go ahead.

**Comment by unkcpz** [comment]
Hi @danielhollas, thanks for the very detail report. However, I can not reproduce the issue. I manage the start/stop container all by using `aiidalab-launch`. The container start always has the same ID. Are you also use aiidalab-launch for your case? 
But I think the issue you report still exists and is crucial, I can image in the production deployment if the user starts their Jupyter entity which will close and start a new container from image, the `/opt/conda` folder will renew.
Instead of installing the pip to `/home/jovyan/.local`, it would be more proper to mount whole `/opt/conda` to a volume.

**Comment by danielhollas** [comment]
I don't think mounting /opt/conda is a good solution, we need to preserve what is pre-installed in the Aiidalab docker image. It would also added yet more complexity, we already have two volumes.

I'll do more tests, it's possible I was manually removing the container.

Why do you think installing to .local is bad? That's what has been happening up till now and worked.

**Comment by unkcpz** [comment]
> Why do you think installing to .local is bad? That's what has been happening up till now and worked.

I didn't mean bad, just there were some unclear implementations to me. I didn't take a close look at 
1) which folder will go first and where is the PATH priority set 
2) how do the aiidalab AppStore version checks work. 

When @csadorf was there, I was always lazy to figure out all details 🤣 I think now we have to start dig more and share his knowledge.  

> I'll do more tests, it's possible I was manually removing the container.

Probably, and I'll further test with the production Jupyterhub deployment in THEOS. I think removing the server and restarting it from Jupyterhub panel can reproduce the issue.

**Comment by danielhollas** [comment]
>  I think removing the server and restarting it from Jupyterhub panel can reproduce the issue.

You can probably just prune the containers via docker before restarting via `aiidalab-launch`

```
aiidalab-launch stop
docker container prune
aiidalab-launch start
```

> which folder will go first and where is the PATH priority set

I have already tested that packages installed in `.local/` take precedence. 

The way pip currently works AFAIK is that in tries to do system-wide installation (`/opt/conda`) first, and if it doesn't have access it does user installation (`~/.local`). Because the `/opt/conda` is now writeable, we now have to explicitly instruct pip to always do user installation.

Note that we're not doing anything non-standard here, this is how pip works (with the caveat that python environment and pip itself is managed by conda).

I believe one thing we need to resolve is whether to install `aiida-core` and `aiidalab` via conda (as done now) or via pip, as we've already discussed in one of the PRs. But that is a separate discussion imo.

**Comment by danielhollas** [comment]
> how do the aiidalab AppStore version checks work.

Can you elaborate on this? I'd think this should be independent of how the packages are installed, version checks are coming from `setup.cfg` no?

**Comment by unkcpz** [comment]
> I'd think this should be independent of how the packages are installed, version checks are coming from setup.cfg no?

Yes, that's correct.
