### ISSUE TITLE
AWB external_url missing on manage application page

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab#329]
After installing AWB, I clicked on "Manage application" which brought me to `/apps/apps/home/single_app.ipynb?app=aiidalab-widgets-base`

Here's what I see

![obrazek](https://user-images.githubusercontent.com/9539441/205025918-2a526e63-4fea-4db6-831d-6d5c93f3780a.png)

However, if I run the following command locally in the container

```sh
aiidalab registry parse-app-repo /home/jovyan/apps/aiidalab-widgets-base
```

I get

```
Parsing . ...
{"metadata": {"title": "aiidalab_widgets_base", "description": "Reusable widgets for AiiDAlab applications.", "authors": "The AiiDAlab team", "state": "stable", "documentation_url": null, "external_url": "https://github.com/aiidalab/aiidalab-widgets-base", "logo": null, "categories": [], "version": "attr: aiidalab_widgets_base.__version__"}, "environment": {"python_requirements": ["PyCifRW~=4.4", "aiida-core>=2.0,<3", "aiidalab>=21.11.2", "aiidalab-eln>=0.1.2,~=0.1", "ansi2html~=1.6", "ase~=3.18", "bokeh~=2.0", "humanfriendly~=10.0", "ipytree~=0.2", "ipywidgets~=7.7", "more-itertools~=8.0", "nglview~=3.0", "optimade-client==2022.9.19", "scikit-learn~=0.24", "spglib~=1.14", "vapory~=0.1.2"]}}
```

where the `external_url` is parsed. Therefore I guess this is a bug somewhere here in `aiidalab` repo, not in AWB configuration.

Also note that the error message in the screenshot is also a link that goes to `/apps/apps/home/Field`, which results to 404 page. The error message should not be linked.

**Comment by danielhollas** [comment]
I've looked into this a bit more and this issue seems to affect most of the apps. I looked at what is actually stored in the app registry json files, and the `url` field is there, for example for AWB.

https://aiidalab.github.io/aiidalab-registry/api/v1/apps/aiidalab-widgets-base.json

Perhaps the code wrongly assumes that the field is `external_url` and not `url`?

**Comment by danielhollas** [comment]
For example, the Aurora app is not affected by this bug

![image](https://user-images.githubusercontent.com/9539441/220223962-d102d57b-c657-432f-9b50-b94f52a51f0b.png)

Indeed, in the registry json, there is an `external_url` field, instead of `url`. I don't know how / why there is a difference between these json files between AWB and Aurora, since they both only provide `url` fields in the metadata section of their `setup.cfg`, but in any case, the code needs to read both `url` and `external_url`. I've not yet found where this code that parses this info lives.

**Comment by unkcpz** [comment]
I'll regard this issue to be solved after we [update the metadata](https://github.com/aiidalab/aiidalab-registry/issues/112) for apps which has the problem with this URL field.

**Comment by danielhollas** [comment]
Solved in https://github.com/aiidalab/aiidalab-registry/pull/113
