### ISSUE TITLE
Backport validation of core dependencies to old docker stack

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab#348]
As mentioned in #347, the backport support for old stack is required.

**Comment by danielhollas** [comment]
I would suggest that the easiest path to do this is to make the `aiidalab` package compatible with the old Docker stack again. 
As far as I can see in the git log, there seems to be only one minor breaking change introduced in https://github.com/aiidalab/aiidalab/pull/301, where the `reentry scan` was deleted from post-installation. We can simply check the aiida-core version and run `reentry scan` if on for AiiDA < 2.0

**Comment by danielhollas** [comment]
I'll take care of this one
