### ISSUE TITLE
The app manager keeps on refreshing because of watchdog spamming opened event check

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab#358]
Once the app is installed, the it become "attached" to the app manager and the app manager will keep on refresh to get the latest version information of the app, e.g if the app is latest or if the dependencies are still compatible.. This status refresh is handled by the `AiidaLabApp.refresh` which is running in an independent thread in the background so it is not blocking other operations. 
However, as shown in the recording below, the loading spinner will show every 1 second and when it refreshes all other widgets are blocked and not interactive. 

EDIT: I forget to attach the screencast, thank you for the noticing @danielhollas 
![Peek 2023-03-01 17-43](https://user-images.githubusercontent.com/8831685/222206123-28647eba-afc0-4637-b4b1-62092f3c3c3e.gif)

https://github.com/aiidalab/aiidalab/blob/798b459990a011308c7e14e01d0e295d05345142/aiidalab/app.py#L768-L773

**Comment by danielhollas** [comment]
The screencast is in this comment.

https://github.com/aiidalab/aiidalab/pull/347#issuecomment-1450467387

> Once the app is installed, the it become "attached" to the app manager and the app manager will keep on refresh to get the latest version information of the app, e.g if the app is latest or if the dependencies are still compatible..

Hmm, I've been looking at the code and I didn't find what you describe. Can you elaborate a bit more which part of the code triggers the excessive refresh?

**Comment by unkcpz** [comment]
> Can you elaborate a bit more which part of the code triggers the excessive refresh?

When the app manager instance is created, the `self.refresh_async()` will start the function in another thread in the set interval. 

https://github.com/aiidalab/aiidalab/blob/798b459990a011308c7e14e01d0e295d05345142/aiidalab/app.py#L623

**Comment by danielhollas** [comment]
I am not sure I understand the screencast correctly but I am unable to reproduce the issue.
Admittedly, I do not have much experience with Threads in Python, but the code looks fine to me. The `async_refresh` is called only in the class constructor, and the extra thread will exit after the single refresh, it shouldn't keep refreshing.

I wonder if what you saw is some different underlying bug?

**Comment by unkcpz** [comment]
Ha! Find the mouse. It is the watchdog problem. After I update the watchdog version the problem shows up.
