### ISSUE TITLE
Update button doesn't respect version compatibility

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab#360]
I noticed an issue with the Update button when testing #347 in the old docker stack.
For both AWB and QeApp, the version dropdown correctly filters out incompatible version, but the update button is still active, and upon clicking tries to install the latest (incompatible) version.

![obrazek](https://user-images.githubusercontent.com/9539441/222231811-c200d45f-cbf7-4863-8092-576bcfec46a3.png)

At the very least, we need to update the function `remote_update_status`

https://github.com/aiidalab/aiidalab/blob/main/aiidalab/app.py#L173

**Comment by unkcpz** [comment]
If I understand correctly this only happened for the old stack since for the new stack the latest version will always show in the dropdown list. But the latest version for AWB app in old stack is the 2.0.0 but show be 1.4.2.

**Comment by danielhollas** [comment]
Yes, I discovered it the the old stack, but it is a general problem.
