### ISSUE TITLE
Update MarkupSafe

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [aiidalab/aiidalab#381]
When installing some dependencies this ERROR can occur 
werkzeug 2.2.2 requires MarkupSafe>=2.1.1

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiidalab 23.3.0 requires MarkupSafe==2.0.1, but you have markupsafe 2.1.1 which is incompatible.

**Comment by danielhollas** [comment]
Thanks for the report. I think this has already been solved in https://github.com/aiidalab/aiidalab/pull/388, but it was not released yet. 
@AndresOrtegaGuerrero can you please specify which app is affected by this? Maybe we should make a new release...

**Comment by AndresOrtegaGuerrero** [comment]
I think this was happening in qe_app, but I am not having this error anymore. I will close this issue :)
