### ISSUE TITLE
core packages checking from pip-compile list

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab#397]
From what I raised in https://aiida.discourse.group/t/update-aiida-core-version-ask-for-db-migration-do-it/43/5, I foresee a potential issue with the current "core package" feature. 

Things were a bit tricky on AiiDAlab, since in AiiDAlab, different apps/plugins share the same Python environment therefore a single `aiida-core` installation. There is a possibility that installing/updating the app will override the `aiida-core` that shipped with the aiidalab docker stack. 

It may be not a big issue if the `aiida-core` is updated and database can be migrated. There is a chance that plugin is pinning to lower `aiida-core` version and will install a `aiida-core` that has a lower database version compatible. The database can not downgraded so this will break the whole AiiDAlab instance. 

@danielhollas @yakutovicha I think we need to give more detailed "core packages" checking in aiidalab to prevent core dependencies from being overridden by the dependencies. For instance, in QeApp, we didn't specify the `aiida-core` as dependencies but `aiida-quantumespresso`, and it will then need `aiida-core>2.3.1` for example, and override the what limited as core packages without raising exceptions.

I am not sure if it is a good idea that in the `aiidalab-docker-stack`, we set the `aiida-core` with a more strict version range that prevents the user from downgrading it to the version where the database is not compatible.

**Comment by danielhollas** [comment]
Yeah, I agree that the DB schema upgrades / downgrades are indeed problematic. I would vote for pinning the aiida-core minor version in the image, seems like the only solution to avoid this and should make things more stable overall. If an app needs a newer version, the user would need to download a newer image.

**Comment by danielhollas** [comment]
We've pinned the aiida-core version in the docker stack recently so I believe this can now be closed.

https://github.com/aiidalab/aiidalab-docker-stack/pull/440
