### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab#403]
Here's a test that's currently failing:

```python
    def test_get_all_tagged_releases():
        """Test that all tagged releases are returned."""
        url = "git+https://github.com/aiidalab/aiidalab-qe.git@*:v23.04.0^.."
        base_url, release_line = _split_release_line(url)
    
        with fetch_from_url(base_url) as repo_path:
            repo = GitRepo(os.fspath(repo_path))
            releases = [tag for tag, _ in _get_release_commits(repo, release_line)]
    
        print(len(releases), releases)
>       assert "v23.04.2" in releases
E       AssertionError: assert 'v23.04.2' in ['v23.04.0', 'v23.04.1', 'v23.10.0a0', 'v23.10.0a1', 'v23.10.0a2', 'v23.10.0b0', ...]

tests/test_registry.py:17: AssertionError
```
It is very strange since I can see the `v23.04.2` on Github here: https://github.com/aiidalab/aiidalab-qe/releases/tag/v23.04.2

@unkcpz do you know what happened to this release? 
The one thing I noticed that the commit corresponding to it is not on any branch on Github (which is perhaps why the test is failing). Was the original branch deleted by accident? https://github.com/aiidalab/aiidalab-qe/commit/f45af14167e561822cb3e39802bb2b478d3f45d2

**Comment by unkcpz** [comment]
No idea.. I need to take a close look. If I remember correctly, from `v23.4.2` the releases are supposed to coming from support branch. And there was an issue in aiidalab/aiidalab that the version not able to picked from branch other than default branch, but that was fixed. 

At that time, the steps on how to make the support release was not clear enough. The release management is now summarised in https://github.com/aiidalab/aiidalab-qe/wiki/Releases-management

**Comment by unkcpz** [comment]
I guess I delete the support branch by accident when prepared the `support/23.10.x`. I add the `support/23.04.x` back from `v23.04.6`, and the test should pass now (test test is failed for py38 but with another reason, I'll investigate in separately). So close this issue.

**Comment by unkcpz** [comment]
By the way, a good chance to pinning @AndresOrtegaGuerrero @mikibonacci @superstar54 to go to `aiidalab-qe` to check the branches with ongoing or staled PRs. And in the future, please try to open PR from your forked repo. I open a conversation on discourse https://aiida.discourse.group/t/clean-branches-of-qe-app/236, let's discuss there.
