### ISSUE TITLE
`aiidalab install` with version does not work

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab#404]
```
aiidalab install quantum-espresso>=v24.04.0a1
```
Run the above command will install `quantum-espresso==v23.10`, and redirect the output to a file called `=v24.04.0a1`.

**Comment by danielhollas** [comment]
Heh ,I've ran into this as well. You need to escape the with quotes (both single/double should work).

```bash
aiidalab install "quantum-espresso>=v24.04.0a1"
```
This is standard unix behaviour, I don't think we can do anything here.

**Comment by superstar54** [comment]
I see. Thanks!
