### ISSUE TITLE
Add a possibility to pip install the app dependencies

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab#41]
It would be desired to allow pip install dependencies. 

Use [repo2docker](https://repo2docker.readthedocs.io/en/latest/config_files.html) as an example.

**Comment by csadorf** [comment]
@yakutovicha Since I'm working on this, can you assign me this issue?

**Comment by yakutovicha** [comment]
> @yakutovicha Since I'm working on this, can you assign me this issue?

done!
