### ISSUE TITLE
Error installing aiidalab-qe-vibroscopy 

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [aiidalab/aiidalab#425]
When opening a new container (arm64 aiidalab/full-stack:latest , also on edge) i get this error 

![image](https://github.com/aiidalab/aiidalab/assets/34098967/558c408b-8de1-4feb-a999-826e8b6ecac9)

**Comment by danielhollas** [comment]
We've just released a new version of the image where this problem should be solved. @AndresOrtegaGuerrero please confirm.
