### ISSUE TITLE
pip automatically installs into `/.local` directory

### ISSUE THREAD

**Issue by csadorf** [aiidalab/aiidalab#65]
# Observed behavior

Installing a Python package with `pip install <package>` installs the package into the `site.USER_SITE` path as if the `--user` argument was provided.

# Expected behavior

Installing a Python package with `pip install <package>` should install the package into the environment prefixed path.

# Additional notes

This might not actually a bug, but at least to me presents unexpected behavior with potential negative consequences. This should be further investigated.

**Comment by yakutovicha** [comment]
I think I know the answer to this: it seems to be the feature of pip. If the environment prefixed path is inaccessible, then pip switches to the user installation: 
<img width="962" alt="Screenshot 2021-08-04 at 18 16 19" src="https://user-images.githubusercontent.com/13118485/128217078-7a7e67ee-e13e-4654-9cb8-9328e1cced1c.png">

So I think the behaviour is normal and the issue can be closed. Pinging @csadorf.

**Comment by csadorf** [comment]
Indeed, I think this message was not shown (or I just overlooked it) when I first created the issue.
