### ISSUE TITLE
App managing interface.

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab#70]
- [ ] Add a possibility to install an app via the URL.

- [x] Add a checkbox in GUI to install prereleases.

- [x] Add a button to reset the changes.

**Comment by ltalirz** [comment]
@yakutovicha not sure but perhaps some of these items were done/decided not to be done?

**Comment by yakutovicha** [comment]
> @yakutovicha not sure but perhaps some of these items were done/decided not to be done?

Thanks for the reminder. Indeed, most of the requested changes are already taken care of. I slightly modified the description, to better describe the required functionality.

I think the only remaining thing is to add something like `aiidalab install <URL>`. I believe @csadorf is working on it.

**Comment by csadorf** [comment]
> I think the only remaining thing is to add something like `aiidalab install <URL>`. I believe @csadorf is working on it.

@yakutovicha , yes and I am working on it in the context of #201 . However, I have created #213 to keep track of this more explicitly and recommend that we remove that sub-task here and close.
