### ISSUE TITLE
Dependency version clash

### ISSUE THREAD

**Issue by chrisjsewell** [aiidalab/aiidalab#75]
Running `pip check` after installation you get:

```
aiida-castep 1.0.0 has requirement ase<3.18,>=3.0, but you have ase 3.19.1.
```

As confirmed by:

https://github.com/aiidalab/aiidalab/blob/37f581eb9aa95120630dc012d317caa57c00bce3/requirements.txt#L4
https://github.com/aiidalab/aiidalab/blob/37f581eb9aa95120630dc012d317caa57c00bce3/requirements.txt#L30

**Comment by yakutovicha** [comment]
Yep, `aiida-castep` clashes with the other plugins, so I had to move it to the `[dev]` section of the Pipfile:
https://github.com/aiidalab/aiidalab/blob/37f581eb9aa95120630dc012d317caa57c00bce3/Pipfile#L9

The only way to avoid the clash is to delete the plugin from the dependencies.

**Comment by chrisjsewell** [comment]
thanks @yakutovicha, pinging @zhubonan (that aiida-castep owner) about this issue

**Comment by yakutovicha** [comment]
> thanks @yakutovicha, pinging @zhubonan (that aiida-castep owner) about this issue

that is another way ;)

**Comment by chrisjsewell** [comment]
Ah ok so, the quantum mobile install doesn't use the Pipfile: https://github.com/marvel-nccr/ansible-role-aiidalab/blob/453f60635090e1e9017657e284cd83bacff37581/tasks/prerequisites.yml#L39-L45.
I've never used a Pipfile before: what's the command to install with a Pipfile? @ltalirz any thoughts how to integrate this in to the ansible role, I don;t know off-hand

**Comment by yakutovicha** [comment]
We use `pipenv` to pin the version of all the required packages dependencies. Here is how we do it: https://github.com/aiidalab/aiidalab#updating-requirements

**Comment by chrisjsewell** [comment]
or can we quickly comment out aiida-bigdft and aiida-castep from the requirments.txt for now and make another release?

**Comment by chrisjsewell** [comment]
> We use `pipenv` to pin the version of all the required packages dependencies. Here is how we do it: https://github.com/aiidalab/aiidalab#updating-requirements

yep that looks too complicated lol, can we quickly comment them out from the requirements.txt for now?

**Comment by yakutovicha** [comment]
> yep that looks too complicated lol, can we quickly comment them out from the requirements.txt for now?

Well, this won't change anything, right? Only to silence the pip warning.

But in case you really want me to take these packages out, I can do that.

**Comment by chrisjsewell** [comment]
yes please, your right not commented out, actually deleted, so that they are not read in by: https://github.com/aiidalab/aiidalab/blob/37f581eb9aa95120630dc012d317caa57c00bce3/setup.py#L12-L13, and included in the `install_requires`
