### ISSUE TITLE
Install button is always active for the `aiidalab-qe` app.

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab#86]
After the app is installed the `Installed version` appears as unknown, while it is clearly the latest commint on the latest branch.

<img width="1141" alt="Screenshot 2020-07-29 at 16 47 42" src="https://user-images.githubusercontent.com/13118485/88815203-5b5afa80-d1bb-11ea-8c0d-07503046f756.png">

Pressing the `Install` button doesn't change anything.

**Comment by csadorf** [comment]
I've removed the submodules on aiidalab-qe@master, so that will probably resolve the issue. I've tried to make dulwich properly parse the git submodule status, but that turns out to be a non-trivial undertaking that is probably not worth our time.

**Comment by yakutovicha** [comment]
fixed in #114
